definitions:
  http.Response:
    properties:
      data: {}
      description:
        type: string
      status:
        type: string
    type: object
info:
  contact: {}
paths:
  /accounts:
    get:
      consumes:
      - application/json
      operationId: get_accounts
      parameters:
      - description: username
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Response body
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Invalid Argument
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Server Error
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Get all user accounts by your username
      tags:
      - Accounts
  /create-account:
    post:
      consumes:
      - application/json
      operationId: create_account
      parameters:
      - description: user_id
        in: query
        name: user_id
        required: true
        type: string
      - description: account_number
        in: query
        name: account_number
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Response body
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Invalid Argument
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Server Error
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Create online bank account
      tags:
      - Accounts
  /login:
    post:
      consumes:
      - application/json
      operationId: login
      parameters:
      - description: username
        in: query
        name: username
        required: true
        type: string
      - description: password
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Response body
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Invalid Argument
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Server Error
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: Login
      tags:
      - Auth
  /pay-for-account:
    put:
      consumes:
      - application/json
      operationId: pay_for_account
      parameters:
      - description: account_number
        in: query
        name: account_number
        required: true
        type: string
      - description: balance
        in: query
        name: balance
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Response body
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Invalid Argument
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Server Error
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Do payment for an account
      tags:
      - Accounts
  /sign-in:
    post:
      consumes:
      - application/json
      operationId: sign_in
      parameters:
      - description: username
        in: query
        name: username
        required: true
        type: string
      - description: password
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Response body
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Invalid Argument
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Server Error
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: SignIn
      tags:
      - Auth
  /transfer-balance:
    post:
      consumes:
      - application/json
      operationId: transfer_balance
      parameters:
      - description: sender
        in: query
        name: sender
        required: true
        type: string
      - description: recipient
        in: query
        name: recipient
        required: true
        type: string
      - description: balance
        in: query
        name: balance
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Response body
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Invalid Argument
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Server Error
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Transfer balance between accounts
      tags:
      - Accounts
  /withdraw-from-account:
    put:
      consumes:
      - application/json
      operationId: withdraw_from_account
      parameters:
      - description: account_number
        in: query
        name: account_number
        required: true
        type: string
      - description: balance
        in: query
        name: balance
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Response body
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Invalid Argument
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Server Error
          schema:
            allOf:
            - $ref: '#/definitions/http.Response'
            - properties:
                data:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: Withdraw money from a account
      tags:
      - Accounts
securityDefinitions:
  ApiKeyAuth:
    description: Online Banking Service
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
