version: '3.8'
services:
  app:
    container_name: golang_container
    build: .
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      - application

  database:
    restart: always
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=online_banking_service
    ports:
      - '5477:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - application

volumes:
  pg_data:

networks:
  application:
    driver: bridge